services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - agent-monitor-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/agent-monitor?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - agent-monitor-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Changed to use production port
    environment:
      - VITE_API_URL=http://server:3000
    depends_on:
      - server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - agent-monitor-network

networks:
  agent-monitor-network:

volumes:
  mongodb_data:

# Create a .env file with these variables:
# MONGO_USER=admin
# MONGO_PASSWORD=secure_password
# JWT_SECRET=your-secure-secret-key
